### PR TITLE
zrange withscores

### PR DESCRIPTION
**Pull request by BeyondWUXF**

### CODE REVIEW

**Comment by sewenew** [comment]
Thanks for contribution! However, in order to make async interface be consistent with the sync one, we'd better make `AsyncRedis::zrange` to send "withscores" option depends on the type of template parameter, i.e. if the template parameter is a container of `std::pair`, `AsyncRedisn::zrange` sends "withscores".

```
auto res_with_score = async_redis.zrange<std::vector<std::pair<std::string, double>>>("zset", 0, -1);
auto res_without_score = async_redis.zrange<std::vector<std::string>("zset", 0, -1);
```

You can check `Redis::zrange`'s implementation and the related comment in Redis.h for detail.

Regards

**Comment by BeyondWUXF** [comment]
> Thanks for contribution! However, in order to make async interface be consistent with the sync one, we'd better make `AsyncRedis::zrange` to send "withscores" option depends on the type of template parameter, i.e. if the template parameter is a container of `std::pair`, `AsyncRedisn::zrange` sends "withscores".
> 
> ```
> auto res_with_score = async_redis.zrange<std::vector<std::pair<std::string, double>>>("zset", 0, -1);
> auto res_without_score = async_redis.zrange<std::vector<std::string>("zset", 0, -1);
> ```
> 
> You can check `Redis::zrange`'s implementation and the related comment in Redis.h for detail.
> 
> Regards

I've tried this, but it doesn't work. It throw an exception:  not a double reply

**Comment by BeyondWUXF** [comment]
In sync command format function:
`inline void zrange(Connection &connection,
                    const StringView &key,
                    long long start,
                    long long stop,
                    bool with_scores) {
    if (with_scores) {
        connection.send("ZRANGE %b %lld %lld WITHSCORES",
                        key.data(), key.size(),
                        start,
                        stop);
    } else {
        connection.send("ZRANGE %b %lld %lld",
                        key.data(), key.size(),
                        start,
                        stop);
    }
}`

however, in async command format function:
`inline FormattedCommand zrange(const StringView &key, long long start, long long stop) {
    return format_cmd("ZRANGE %b %lld %lld", key.data(), key.size(), start, stop);
}`

**Comment by BeyondWUXF** [comment]
The command sent to redis from the async interface does not have the WITHSCORES paramter

**Comment by sewenew** [comment]
I've already added support for withscores option, please check the latest code on master branch. I'll close this PR.

Thanks again for your contribution!

Regards

**Comment by sewenew** [comment]
Some example:

```
// without score
async_redis.zrange<vector<string>>("zset", 0, -1, [](Future<vector<string>> &&fut) { auto mems = fut.get(); });

// with scores
async_redis.zrange<map<string, double>>("zset", 0, -1, [](Future<map<string, double>> &&fut) { auto mems_with_scores = fut.get(); });
```

**Comment by BeyondWUXF** [comment]
ok，i'll try them

**Pull request closed without merging**
