### PR TITLE
fix issue #537: slot-node mapping not updated correctly.

### PR DESCRIPTION
**Pull request by sewenew**

### CODE REVIEW

**Comment by mike1821** [comment]
Hello @sewenew, thank you very much for providing this fix. 

After applying the new library release we noticed an increase CPU usage in both application and database pods. I was wondering if any of the changes could justify this increase? 

For example I noticed the newly introduced _run thread inside shards_pool.cpp (line#386) which poll the cluster slot map incorporates this while(true) operation without a corresponding delay in it. Do you think this could create a problem?

BR,
Michalis

**Comment by sewenew** [comment]
> After applying the new library release we noticed an increase CPU usage in both application and database pods

How much does the CPU usage increased?

> the newly introduced _run function inside shards_pool.cpp (line#386), which poll the cluster slot map incorporates this while(true) operation without a corresponding delay in it. Do you think this could create a problem?

Although there's a while loop without delay, it only does an update when the state is changed from UPDATED to others. If you create pipeline in a busy loop, this thread sends command to Redis Cluster in a busy loop. However, since the slot updating work blocks on IO, it should not increase CPU too much, especially compared to your busy pipeline loop.

Regards

**Comment by mike1821** [comment]
It is approximately 15% increment in CPU usage.

**Comment by sewenew** [comment]
Can you show me the minimum code that reproduces the problem? So that I can do some debugging. Thanks!

Regards

**Pull request merged**
