### PR TITLE
Keep connection on timeout

### PR DESCRIPTION
**Pull request by StefanKarlsson321**
When reconnect is done due to timeout the output buffer is lost, and it is unknown whether commands sent will or will not reach the server, which can result in lost data. By instead keeping the connection and receiving and ignoring stale messages it is ensured at least that all commands are sent in time.

Timeout test case added in separate commit.

### CODE REVIEW

**Comment by StefanKarlsson321** [comment]
I have done testing on stand-alone redis, with sentinel and cluster:
./test/test_redis++ -h localhost -p 7000 -q 27000 -o 1 <- Passes (5 runs)
./test/test_redis++ -n localhost -c 6379 -o 1 <- Passes <- Passes (5 runs)
./test/test_redis++ -h localhost -p 6379 -o 1 <- Passes <- Passes (5 runs)

However no tests made for subscriber, pipeline etc.

**Comment by sewenew** [comment]
@StefanKarlsson321 I was on a long vacation, and sorry for the late reply.

I checked your changes recently. However, I'm still not sure if it's better to keep receiving stale messages after the operation is timed out:

- Read operations: This won't help, since the stale messages are discarded and we still cannot get the reply.
- Write operations: Even if we receive the result of a timed out operation, the client code still has no idea whether the write operation has been successfully executed by Redis server. Since the connection might be broken, and client code still need to handle the timeout exception, e.g. retry the operation.
- In order to receive the delayed messages, the code will be more complicated.

Also, the async interface is in progress, which might mitigate the problem. So I'll make this RP pending so far.

Regards

**Comment by StefanKarlsson321** [comment]
The only reason for the suggested change is that write operations that has not reached the server and has timed out, will be sent to the redis server and thus our goal of not losing data on write is achieved. On a redis sentinel setup in kubernetes it turns out the most frequent error response is timeout, and although data is lost duing read it can be re-read with a new command when applicable.

**Comment by sewenew** [comment]
> write operations that has not reached the server and has timed out, will be sent to the redis server 

However, IMHO, you can not be guaranteed that it will be sent to server, since the connection might be broken after the timeout. In order to ensure the write operation is done by Redis, you have to retry it.

> On a redis sentinel setup in kubernetes it turns out the most frequent error response is timeout,

In this case, I'd suggest you to increase `ConnectionOptions::socket_timeout`, otherwise, retry operation might make Redis server a heavy load.

**Comment by StefanKarlsson321** [comment]
Basically with the present model it is impossible to tell if a timeout is e.g. the result of a failed write or a failed read, so you don't know whether the write was successful anyway, in particular if you get a timeout error. For our purposes it is quite cumbersome to implement a retry mechanism and convenient to keep the data in the redis output buffer. That way it is also made sure that it is only written once.

The `ConnectionOptions::socket_timeout` has already been increased as far as reasonable by us, but we still experience timeouts when running in a kubernetes environment with redis sentinel.

Nevertheless, I can understand that this is undesirable.

**Pull request closed without merging**
